/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 17.05.2026 17:31:20

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1552;
#else
constexpr int kTensorArenaSize = 528;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,180 } };
const TfArray<1, float> quant0_scale = { 1, { 0.065518252551555634, } };
const TfArray<1, int> quant0_zero = { 1, { -88 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { -30, 19, 12, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0019250360783189535, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  46, -19, 95, -92, -37, 54, 82, -90, -127, 81, 
  79, 97, -48, -79, -110, 7, 16, -94, 4, -42, 
  -112, -50, 111, 11, -84, -89, -84, -36, 110, 34, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0063647739589214325, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 6, 150, 57, 27, -8, -20, -15, 20, 41, 26, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0012015312677249312, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  19, -66, -23, 0, 80, 0, 96, -71, -8, -48, 6, 11, 48, 127, 64, -50, 1, -24, -63, 11, 
  -35, -78, 78, 63, 72, -30, -14, -58, -62, 32, -28, -38, 80, 46, 77, 99, -30, 43, -24, -21, 
  11, -62, 23, 100, -34, -7, -9, 70, -4, 10, 45, 63, -10, -43, 10, -40, 76, -56, -67, -32, 
  55, 23, 79, 13, -43, 65, -49, -30, -11, 64, 85, 42, -49, -66, -27, -38, -20, -27, 89, 69, 
  -49, 32, -74, -48, -76, 55, -17, 17, -73, 28, 59, 46, -31, 34, 30, -73, -27, 66, 45, 43, 
  -77, 50, -51, 35, -27, -116, -4, 51, -90, -42, 45, 42, -45, 41, 9, -62, -23, 49, -50, -14, 
  56, 27, -55, -70, 53, 58, 19, -20, -31, -13, 36, 25, -60, -22, 34, -28, 46, -19, -27, -28, 
  1, 80, 41, 54, -12, 73, 54, -78, 93, -14, -31, 91, 47, -29, -102, 17, 63, 15, 21, 70, 
  58, 44, 60, 41, 83, 33, -85, -11, -6, 21, 85, 24, 7, -46, -39, 77, -63, 65, -15, -14, 
  46, -39, -15, 11, 40, 87, -1, 5, 56, -64, -38, 43, -74, -44, 49, -20, 3, 70, 4, 69, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0052218702621757984, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 350, 160, 527, 397, 619, 340, 19, -280, 116, 345, 431, 605, 613, 183, 134, 453, -228, 413, 111, 296, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00014597084373235703, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*180] = { 
  -10, -14, -26, 82, 4, 15, -2, -74, 0, -82, -24, 6, -90, -72, -43, 58, 16, 54, -18, -55, 45, -43, 40, -11, -90, 28, -58, -58, -74, -94, 8, 20, 49, -44, -90, 11, -72, 30, -33, -71, 12, -29, -80, -46, -82, 55, -31, 79, -31, -74, -35, -95, 6, -42, -86, 27, 51, 35, 54, 27, 21, -34, 26, -35, -31, -75, -22, 0, 39, -30, -3, -86, -69, -42, -40, -50, 49, 56, 8, 44, 3, -23, -34, 1, -33, -9, -96, -27, -76, -90, 20, -23, -19, 82, -26, -92, 52, 19, -80, -48, -24, -96, -4, 20, -44, -38, -35, 21, -24, -54, 39, -1, -21, 25, -59, 49, -56, 5, -97, 4, 29, -3, 39, 88, -94, -32, 28, -17, 39, -29, -84, -63, 53, 3, 41, -47, -1, 93, -1, -13, 5, -33, -82, -79, -61, -48, -49, 5, -77, -49, -42, 40, -4, 63, 6, -59, 27, -13, -106, -33, -4, 27, -74, -63, -38, -43, -60, -43, 66, 47, -69, -43, -47, -51, -40, 29, 14, 11, -78, -65, 
  -113, -8, 46, 19, -27, 4, 16, 15, 26, 62, -58, 23, 1, 5, 22, -78, 55, 25, 87, -49, -22, -16, 55, -22, 31, 28, -22, 47, -27, -79, -49, 65, 55, 84, 52, -34, -71, -17, 10, -44, -41, -52, 65, 44, 32, -57, 48, -63, 16, 0, -79, -18, -6, -38, -19, -86, -82, 52, 55, -77, -49, 44, -38, -4, -20, -8, 49, -85, 34, -29, 61, -52, 37, -13, -10, 27, -32, -46, 4, 66, -16, -84, -46, -7, 29, -1, -22, -62, 8, -35, -13, 14, 67, 26, 4, 37, -44, -72, 4, -74, 10, 66, -7, -17, -74, -1, 48, -50, -5, -16, -37, -82, 60, 7, -36, 52, 5, 1, -72, -70, -17, -79, -23, -31, 33, -16, -12, 18, -75, 62, -36, -32, 39, -33, 55, 8, -56, -24, -3, 48, -104, -18, -35, -61, -28, 17, 17, 6, -60, -47, -77, -31, -35, -21, -35, 28, 23, 47, -76, -63, -71, -88, 16, -61, -64, -66, -62, 11, -58, -25, -33, -65, 17, -41, -31, 32, 23, -42, -59, -46, 
  15, -29, -77, -65, 51, -57, 33, 51, 60, -28, -77, -5, -73, 20, -76, 18, 4, 37, -9, 51, 59, -87, 28, -74, -9, -38, 55, 20, -57, -92, -75, 29, 31, -66, 4, -49, -95, -36, 13, -79, 17, 16, -95, -36, -4, -51, -63, -69, 17, -2, 18, -46, -46, -36, 22, -83, -13, -11, -12, -53, 33, -49, -19, 2, -5, 23, -12, -75, -57, -44, -24, -96, -16, 44, -46, -102, -86, 35, -49, -30, 12, -69, -3, -35, -11, -6, -39, -21, -81, -32, -91, 41, 12, -38, 93, 27, -8, 3, -10, 2, -97, -91, -64, -80, 3, -68, 45, 49, -4, 2, -57, 11, -27, -96, -64, -83, 16, 57, -38, 4, -77, 40, 73, -85, 82, 45, -6, 20, -96, -21, 24, -66, -5, 18, 10, -1, -61, 51, 35, 42, -34, 37, 36, 34, -82, -21, -87, -16, -51, -18, -6, -61, -32, -3, 45, 50, 13, -58, 25, -78, -17, 30, -8, 44, -29, -86, -50, -18, -38, 2, -86, -52, -29, -106, -46, -10, 21, -62, -64, -94, 
  -68, 61, -62, 67, -29, 20, -28, 56, 21, -91, 37, 36, 12, 22, 19, -22, -37, -59, 47, 24, -76, 7, -73, -51, 20, 13, -81, 19, 38, 35, -38, 52, 45, -12, 22, -18, 45, -105, -18, 26, -90, 20, -26, 32, 60, -62, 17, -57, 68, 10, -75, -30, -45, -108, -5, -83, -90, -100, -56, -22, 66, 47, 71, 77, -77, -95, 15, -97, -80, -95, 19, -66, -67, -81, 1, 24, 2, 79, 49, 49, -10, 22, 23, -54, -39, -87, -32, -55, 21, -44, 30, 47, -63, 31, 38, -55, -73, -43, 32, -43, -50, -32, 36, -70, -52, -4, 30, -24, 36, -3, -90, -15, -30, 28, -20, 44, -95, -22, 28, -17, -71, 82, 2, 46, -89, -22, -28, -75, -10, 0, -54, -94, -45, 42, -28, -37, -30, 9, 28, 29, 20, 23, -9, -58, -12, -9, -58, -78, -52, -68, -22, -29, 51, 91, -72, 0, 0, 47, -71, -89, -52, 8, 37, 20, -54, 18, -8, -66, 51, -10, -98, -60, -27, -95, 21, 10, 2, 9, 30, -89, 
  57, 39, -4, -42, -76, -33, 84, -2, -21, 71, 3, 39, -24, -10, -80, 34, 67, 32, 0, -32, 19, 95, 7, 9, 4, 31, 83, 79, -43, -91, 27, -27, 49, -49, -39, -7, 5, -42, 44, 75, 38, 53, -37, 2, 7, -56, 79, 27, -9, 37, 84, 91, -25, 15, 14, 109, 84, 95, 102, 9, -75, -40, 50, 77, -11, 75, -2, 107, -45, 13, -35, 52, 85, 58, 1, 26, -3, -40, -31, -45, 89, -41, 70, -22, 58, -11, 49, -23, 84, -60, -38, 25, 0, 57, 7, 20, 15, -28, -73, -35, 4, -49, 36, -4, 39, -51, -51, -38, -45, 10, -30, 4, -47, -8, 52, 14, -10, -33, -22, -42, 58, 0, -65, -3, -80, 28, 91, -43, -20, 56, 0, 10, 54, 10, -48, -28, 60, 19, -65, 40, 44, 24, 54, 10, 75, -52, 80, 34, -45, -101, -19, 58, -47, -45, 22, 100, 76, -32, 76, -32, -5, 71, -47, 5, -108, -61, 35, -46, 75, -37, 4, -58, -55, 44, 69, 37, -6, 65, -1, -7, 
  -34, 67, -33, -15, -10, -68, -1, 66, -41, 11, -78, -35, -83, 29, 52, -12, -61, -20, -35, 25, -65, -69, -14, -45, 51, -25, 16, -16, -42, 113, -26, -1, 19, -59, 38, -77, 47, -49, 27, 61, 47, 23, -59, -27, 59, -86, -52, -89, -14, 69, 61, -16, 21, -35, 27, 39, 19, -16, 37, 43, 10, -68, 16, -72, -2, -6, -32, 58, 64, 29, 66, -40, 47, -62, -43, -60, -3, -43, 37, 19, -63, 26, -40, 60, -10, -63, 19, -8, 72, 25, -1, 9, -77, 47, 23, 0, -1, 34, 8, 53, -4, 30, 69, -37, 52, 1, 79, -82, 14, 62, -15, -14, 16, 37, 47, 7, 30, -67, 13, -9, -87, 48, -90, -1, 23, 65, -19, -36, -44, -75, 0, 19, -55, -33, 50, 54, 37, -92, 47, 93, 23, -19, -17, -60, -7, -62, 49, 52, 48, 16, 44, 25, -7, -82, 72, -21, -35, 51, -38, -21, 28, -91, 23, -78, 105, -91, 81, -77, 30, 25, -18, 51, -76, -9, -78, 7, -74, -36, 61, 92, 
  54, -25, -40, -74, -45, -60, -12, 67, -15, 21, 13, 10, 16, 60, 25, 4, -33, -52, 43, 62, -20, 31, -19, 65, -16, 9, 94, -47, 79, 19, 68, -72, -13, -41, -56, 63, -44, 61, -32, 91, 9, 35, 12, 22, -38, -50, 74, -58, -39, -10, -34, 88, -37, 79, 38, 7, 23, 81, 59, -24, -32, 7, 36, -78, 45, 37, -45, 78, -26, -29, 28, 84, -6, 52, 26, 61, 35, 40, 2, -24, 73, 70, 31, 52, -32, -8, 63, 35, -20, -29, -40, 47, -53, 39, -15, -65, -27, -37, -59, 1, -37, -35, 12, -13, 79, 4, -13, -74, -73, 8, 5, 51, 62, -65, 27, -9, 52, -21, -56, -22, -25, 16, -81, -31, -18, -53, 7, 49, -4, -57, 42, -63, 3, 46, 59, 75, -58, 22, 22, 84, 37, 55, -19, -65, -50, 16, 61, -60, 67, 52, -37, 74, -17, 33, -24, -62, 24, -20, 63, -31, 81, 35, -8, -46, 51, -16, -25, 28, 22, 23, -69, 64, 59, 87, 41, -56, -67, -24, 36, -13, 
  71, -55, 23, 87, 44, 21, 27, 41, -13, 60, -19, 73, -28, 29, -34, -59, -4, -40, -30, 49, 61, -47, -36, 5, -22, 70, -24, 18, -75, 7, 32, 92, 18, -46, -51, -76, -16, 20, 52, -31, -18, 18, 74, 70, 45, 6, 37, -66, -24, 15, -57, -23, -16, 11, -30, -53, -71, 48, 46, -57, -38, -4, 37, -34, 19, 17, 16, -33, -36, 73, -51, 9, -19, 27, 18, 27, -7, 41, -18, 16, 72, -79, 44, -4, 15, -78, 28, 29, 47, -8, -6, -44, 7, -22, -85, -32, -18, -54, 17, 69, -24, 46, -2, -67, 9, -14, -13, -70, 93, -49, -45, -58, 21, 44, 63, -33, 57, -14, -30, 49, -13, 42, -11, -43, 7, 27, -51, -61, -11, -16, 42, -7, -19, 11, -33, 58, 6, -18, 27, -29, -10, 49, 52, 71, 27, 48, -3, -56, 51, 32, 53, -11, 7, 66, 24, 19, -28, 15, -6, -27, -11, -66, 17, -15, 2, -14, -56, 30, -52, -40, 45, -21, -19, 19, -69, 41, -40, -76, -39, 4, 
  32, 83, 4, 1, -82, 43, -8, -44, -4, -20, -1, 42, 40, -33, -7, -43, 40, -68, 90, -1, 64, 50, 68, 31, 39, 42, 48, -14, 57, -82, 33, -66, -36, 14, -78, -32, -77, 56, -60, -3, -49, -50, -80, -40, -70, 14, -21, -23, -26, 8, -83, -87, 65, -60, 27, 25, -2, 24, -20, -34, 40, -12, 58, -16, -12, -83, 56, 45, 38, -49, -43, -33, 3, -72, -38, -77, -50, -37, -29, 49, -47, -54, -69, -45, 55, 7, -13, 18, 35, 35, -7, -65, -72, -3, 44, -15, 59, 8, 23, -52, -63, -56, -45, 24, -6, 49, -13, 6, 34, -23, -46, 38, 0, 22, 49, 60, 14, -60, 53, -30, 48, 69, 8, -9, 25, -79, 5, 66, -79, 51, -77, 53, -85, -29, -67, -9, -49, 69, 33, 53, 43, -26, 31, -64, -84, -11, 11, -74, -91, -38, 58, 50, -43, -37, -52, 26, -95, -91, 23, -32, 27, -11, -6, -79, -14, -83, -58, 17, 33, 3, 49, -25, -4, 44, 50, -48, 44, -39, -93, 36, 
  -66, 47, -122, 6, -57, 23, -96, -28, -71, -99, -88, -76, -100, -43, -55, 59, 5, -9, 66, -63, -39, 23, -13, 43, 56, 30, -19, 0, -25, 29, -35, -10, -107, 10, 40, 1, 27, 31, -40, -10, -4, 10, -64, -4, -36, -77, 62, -4, 78, -77, 20, 50, -100, -99, -64, -5, 24, -12, -90, 21, -68, -29, -80, 70, -17, -39, -96, -48, -79, 13, -69, 31, 46, -19, -20, -57, 84, -45, -65, 36, 18, 50, -91, -70, -74, 39, -74, -62, 16, 12, 64, 42, -49, 2, -7, 49, -25, -96, -84, -54, 27, -81, -88, -49, 7, 0, -65, -64, 43, 13, 15, -65, -57, -59, 46, 30, 40, 22, 30, 38, 65, -62, -58, 77, -58, 14, 32, -50, -64, 11, -56, -65, -49, -43, -66, 40, 81, -29, 23, -89, 38, -76, 4, -29, -13, 7, 49, -28, -98, -5, -73, -59, -71, -47, 54, -87, -86, 13, -92, -35, -38, -98, 12, 10, 2, -75, -20, -75, 7, -57, -5, 32, 26, -49, -90, -66, -15, -76, 35, -15, 
  69, 23, 13, -66, -55, -42, 38, 6, -11, 7, -72, 12, 9, -71, 32, -50, 1, -18, 36, 25, -79, 27, -79, 52, 46, -29, -50, -38, 41, 43, -80, -60, -77, -8, 85, 48, -44, -82, -82, 4, 10, -29, -16, -44, -29, 49, 5, -85, 54, 36, -42, -69, -39, -30, 39, 51, -68, -50, -1, -20, 16, 27, 42, 60, 23, -92, -90, 11, 11, 6, 43, -9, -35, -49, -12, 65, 23, -53, 42, 79, -47, -72, 2, -73, -47, 37, -42, 5, -44, -48, -6, 71, 32, -33, -6, -9, -58, 11, -85, 25, 52, 34, 23, 19, 24, -41, 2, -74, 66, 8, -43, -26, -4, 6, -97, -14, -47, 41, -53, -52, -43, -64, -49, -50, 66, 18, -79, -8, 10, -86, 32, -51, -77, -91, 15, 19, -11, -76, 78, 52, -71, -97, -76, -20, -53, -114, -48, -68, -9, -23, -10, 40, 29, 75, -39, -77, -67, -25, -46, -33, 28, -101, 24, -8, 2, -3, 23, -56, 4, 9, 23, -56, -68, -99, 32, 37, -1, -24, -1, 81, 
  35, 58, 77, 12, -96, -77, 77, -26, 62, -31, 56, 62, 41, 62, 10, 80, -1, -17, 105, -34, -28, -21, 74, 4, 11, 19, 38, 27, 67, 67, 39, 15, 15, 4, -15, -31, -65, 9, 10, 27, 20, 42, 53, -26, -4, 21, 48, 47, -31, -43, -73, 38, 10, 13, 55, 29, 23, -29, -7, -24, 104, 72, 9, 14, 18, 32, 38, -31, -27, -32, -73, -11, -57, -60, 99, 67, 65, 72, 69, -23, 21, 57, -76, -53, -87, -83, -64, 22, -23, 87, 84, -29, -64, -22, -22, 24, 44, 65, 2, -23, -9, -3, 60, 56, 86, 74, 40, 86, 35, -102, -25, 14, 34, 29, -81, -60, -80, -3, 40, 65, 121, 101, 17, 20, -42, -33, -51, -67, 69, 44, -60, 33, 19, -28, -30, 61, -26, 71, -2, 7, -15, 6, -11, 35, 40, -80, -7, -40, -62, 0, 99, -13, 4, 42, -47, 19, 35, 80, -1, -29, 59, -31, -4, 30, -29, 78, 2, -34, 85, -23, 17, 3, 67, -29, 52, -11, 61, 67, -26, 102, 
  -17, -44, -28, -30, 34, -44, -25, -55, -43, 61, 5, -48, 42, 64, -54, 72, 39, -60, 58, -32, 59, 65, -28, 68, 62, -2, 28, -14, 87, -55, -18, 48, -112, 64, 36, 74, 87, -26, -41, -21, 17, 38, -36, -11, -127, -17, 101, 4, -17, 65, 78, -42, -51, 40, -23, -48, -25, 51, 12, -13, -14, -26, -101, 45, -1, 42, 73, 51, 28, 76, 23, -13, 58, 73, -16, -63, 0, 16, -72, -79, 34, 54, 85, 70, 93, 80, -49, -23, 24, 5, -42, 99, -27, 8, -66, -59, 23, -7, 31, -1, -39, 56, 48, 35, -37, -52, 24, 19, 34, -1, 7, -25, -5, -49, -37, 24, -26, -15, 79, 4, 56, 21, -17, -47, 13, 45, -67, 49, -37, 81, 10, 56, 76, 9, -10, 83, 70, -48, 54, 65, 63, 24, 63, -20, -12, -6, -60, 69, -10, -121, 32, -27, -48, 19, -16, 93, -42, 51, -23, -17, 76, -5, -59, -12, -98, -61, 26, 35, -40, -54, 85, -38, -67, 27, 55, 66, -13, 34, -17, -116, 
  51, -69, -21, 6, 55, 93, -56, 79, -4, 56, 37, 39, 86, 39, -23, -25, -69, 9, -52, -43, -35, -48, 6, -16, 4, -49, -27, 91, 12, -11, 53, -63, -35, -64, -26, 60, 71, 26, 92, 18, 113, 79, 104, -15, 45, -7, 10, 65, 87, 31, 74, 84, -11, 8, 120, 19, 63, 103, 88, -34, 30, -13, 7, -49, 35, 105, 108, 105, 59, 119, -18, 31, 94, 31, 18, -28, -29, -16, 47, -60, 17, 81, 22, 18, 90, 60, 104, 114, 44, -98, 33, 29, -33, 52, -89, -44, -33, 69, -4, -20, 28, 79, 31, -45, -68, 58, 11, 12, -11, 19, 81, -52, -37, 30, -12, 76, 75, -12, 76, -86, 21, -19, -17, -15, 56, 53, -28, 90, 56, 106, -24, -21, 60, 37, -78, -44, 44, -10, -26, 48, 97, 8, 54, -66, 15, 86, 67, -10, 74, 49, -2, -48, -43, -49, -24, 98, -29, -4, 53, 2, 15, 81, 68, 46, -15, 33, 59, -49, -47, -39, 99, -15, 33, 25, 15, -29, 48, 86, 18, -19, 
  77, -39, -42, 21, -28, -19, -14, 45, 54, 55, 103, -49, -39, 102, -86, -23, -43, 6, 49, -92, 93, 99, -17, 77, -44, -17, 17, -35, 89, -32, 84, -16, -44, 53, -42, -18, -25, 54, 98, -40, -45, 96, -41, 83, -28, 52, -3, -65, -69, -62, 17, 69, 61, 23, -28, -18, 101, 13, 99, -52, 9, 58, -66, 75, -19, 101, 102, 85, 24, 71, 39, -15, 101, 1, 61, 41, -5, -5, 4, -22, 70, 41, -18, -1, 41, -33, 87, 35, -35, 6, -31, 51, -40, 49, -94, 15, 74, 73, 74, 96, -54, 88, -34, 73, -69, -24, 75, -94, -25, -75, -17, 16, 92, 58, -53, 64, 93, -48, 76, 58, -36, 18, -30, -40, -85, -42, 16, 95, 93, -34, -9, -28, 15, 16, 50, 44, 101, 20, -58, 29, -2, 53, -1, -15, 77, 75, 52, -24, 68, 52, -18, -21, 45, 54, 9, -16, 2, 69, 3, -39, 54, 72, 29, 18, -62, -33, 65, 8, 57, -72, 75, 64, -7, -15, -37, 68, 98, 74, 53, 45, 
  9, 40, -11, -55, -48, 18, -20, 0, 15, 32, -4, 27, -46, 33, 49, 69, -13, 79, 45, 69, -70, 56, -74, 22, 24, 3, -34, -28, -14, -34, 29, -52, 19, 58, 15, 23, 2, -72, 17, 77, 52, -30, 29, -48, 62, -38, -93, 31, -39, 70, 42, 0, 58, 68, 43, -33, 77, 44, -46, 69, 12, -71, 65, -16, 26, 40, 16, -44, 7, 59, -58, 71, 70, 75, 37, 65, -55, 68, 83, 42, -44, -39, 14, 75, 88, 69, 17, 50, 54, 83, 7, 53, 68, 67, 87, 48, -76, 24, 26, 33, 53, 61, 67, -30, 55, -40, -10, 80, 95, -34, 29, -65, -80, 6, 54, -41, -20, -61, 4, -5, -32, -11, 35, -9, 40, -9, -39, -33, -20, -47, -4, -14, 25, 75, -50, -21, -77, 18, 27, 25, -34, 24, -36, -11, 72, 21, 80, 16, 2, -58, 48, -71, 10, 79, 64, 37, -39, 46, -47, -54, -35, 79, -56, 50, 7, -14, -108, 95, 68, 23, -10, -40, -52, -63, 51, 82, -3, -68, -60, -18, 
  11, -57, -6, -14, 52, -13, -8, -32, 54, -68, -64, -19, 23, 43, -43, 39, -69, -13, 24, -34, -61, -32, 47, -13, 32, -23, -10, 63, -50, 41, 39, -8, 84, -56, -32, -41, 28, -57, -23, 0, -2, -14, 13, 56, -23, -53, 53, -55, -15, -36, 0, -10, -11, -51, -19, -80, -18, -22, 44, -64, -41, 59, -34, -4, -59, 34, 6, -20, 9, 70, -65, -17, -41, 66, 49, 49, -43, 29, -55, 10, 13, 70, -73, -19, -11, 47, 0, -51, 69, -31, 17, 68, 81, 3, 6, -24, 24, -5, 87, -27, 0, 2, 0, 2, 60, 62, 29, 86, -23, -53, 52, 38, 77, -47, -68, 32, -13, 77, -36, -74, 44, -17, -31, -18, 63, 15, 1, -55, 85, 66, -15, 62, -11, 18, -60, 8, 48, -31, 63, -83, 72, -1, 66, -8, -36, 32, 81, 56, 6, 7, -35, -15, 81, 23, -20, -27, 52, 84, -34, -19, -64, 33, -8, 66, 51, -36, 66, -45, -30, -4, 42, 2, 55, 78, 30, -16, 42, 63, -69, 61, 
  -43, 40, 77, 77, 34, -29, -35, 59, 21, -14, -32, 70, -32, 50, -77, -53, -52, 31, 94, -65, 37, -37, -62, 71, -45, -64, -43, 21, -10, -66, -37, -56, 15, 42, -15, 72, 69, -46, 50, -69, -77, -27, 73, -28, 7, -77, 8, 87, -36, 15, -40, -49, 67, 36, 18, -62, 53, -72, -21, -54, -3, -59, 51, 95, -38, 37, -13, -2, 21, -26, 55, -32, 45, 66, 16, -8, -61, -43, 79, -82, -66, -74, -72, 9, 36, 68, -34, 14, 13, 16, -28, 75, -56, -17, 33, 35, 26, -36, 60, -75, 62, 26, 0, -52, -64, -104, -60, 88, 43, -98, -74, -41, 54, -3, -57, 19, 49, 71, -43, -30, -72, 72, 36, 90, -21, 29, 31, 61, 68, 63, 36, 29, -51, 56, -14, -42, 75, 62, 39, -39, -82, -76, -77, 47, 35, -6, 17, 27, 60, -22, 10, 66, -59, -33, 0, -26, -22, 23, 25, -43, -65, -75, -80, -10, 46, 29, -67, -22, 86, -7, -80, -30, 46, 50, 54, 56, 10, 6, -32, 41, 
  -104, -3, -2, -61, 29, -5, -61, -17, -12, -39, -83, -41, -78, -66, -70, -78, 20, -84, -28, 23, -50, 53, -52, 51, -46, -79, -15, -34, -81, -61, -2, -20, -85, -55, 71, 47, 9, -64, -71, -40, -70, 2, -60, 26, 7, -49, 88, -17, -47, -75, -13, -82, 20, -59, 32, -72, -67, -66, -38, 56, -61, -29, -82, 75, 33, -54, 54, -75, -8, 53, 34, 28, 44, -49, -78, -13, 80, -14, -9, 21, 9, 21, 56, -13, 24, 1, 53, -5, -17, -61, -111, 71, 23, -11, -59, -66, 33, 9, 64, -58, -88, 66, 8, -3, -43, -34, -28, -82, 18, 38, -70, -6, -91, -55, -61, -75, 18, 15, -84, -68, 31, -30, -44, 28, 16, 61, -28, -44, -7, -7, -81, -48, -10, -17, -12, -80, 32, 51, -19, 19, 27, -47, -32, -52, 35, 29, -8, -2, -40, -5, -43, 44, 38, 48, -8, -62, 17, -49, 56, -38, -4, -58, 4, -86, -6, -106, -16, 51, 8, 39, 44, -72, 61, 45, -29, 19, -67, -57, 36, 66, 
  -12, 72, -33, -43, -4, -27, 24, -8, 59, 48, -65, 59, 51, -3, 12, -41, 10, -98, -46, 32, -31, -72, 60, -62, -8, 0, -52, -35, 25, 70, -64, 23, 34, -53, 19, 21, -79, 7, -6, -15, -56, -59, 15, 37, 18, -72, -62, -7, -12, 15, 15, 28, -74, 16, 32, -44, 36, -69, -57, 77, -68, 62, -81, 23, -48, -13, -19, -61, -65, -49, -78, 47, -27, -15, -9, 18, -54, -97, -73, -24, 57, -10, -8, -72, -17, 26, 66, -10, 20, 13, -81, 21, -72, -22, 34, -70, -62, -68, 63, -50, -30, 52, 46, -66, -6, 39, -64, -75, -11, 56, 64, 41, -84, -68, 22, -3, -21, -57, -48, 7, 67, 21, 14, -44, 33, 43, -80, -13, -54, -5, -62, -6, 54, 36, 21, 66, 45, 39, -46, -18, 0, -80, -4, -10, -28, 31, -84, 30, -46, 60, -89, 50, -40, -33, 15, -95, -86, -41, -28, 17, -85, -99, 35, -48, 53, -77, 63, 20, 59, -40, -45, 30, 7, -39, -3, 27, -76, -13, -66, 7, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,180 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0022279417607933283, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.23009595274925232, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.30245161056518555, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.58381748199462891, } };
const TfArray<1, int> quant9_zero = { 1, { -1 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 180, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 3600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 192), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_979831_21_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_979831_21_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_979831_21_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_979831_21_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_979831_21_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
