/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 15.05.2026 16:52:19

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1456;
#else
constexpr int kTensorArenaSize = 432;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,90 } };
const TfArray<1, float> quant0_scale = { 1, { 0.3556111752986908, } };
const TfArray<1, int> quant0_zero = { 1, { -106 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[6] = { -20, -22, 13, -5, -15, 4, };
const TfArray<1, int> tensor_dimension1 = { 1, { 6 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0060354932211339474, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[6*10] = { 
  53, 59, -31, 15, -109, 35, 2, 37, -54, 14, 
  58, -61, -82, 33, -4, -22, 24, -3, 16, -74, 
  -93, 119, -72, -70, 96, 111, -88, -16, 32, 14, 
  25, -82, 37, -86, 64, -89, -122, -21, -113, 21, 
  41, -74, 8, -127, -65, 37, 54, 37, 85, 30, 
  -69, -33, -67, -17, 33, -120, 98, 46, -65, 59, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 6,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0070017552934587002, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -20, 33, 4, -8, 42, 45, 31, -1, 38, 4, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0031590557191520929, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  32, -127, -50, -14, 98, 8, 118, -65, 3, -47, 33, 19, 62, 99, 9, -33, 20, -27, -50, -4, 
  -30, -91, 72, 98, 53, -20, -37, -74, -67, 36, -27, -23, 65, 15, 93, 69, -35, 42, -32, 44, 
  -13, -68, 1, 77, -32, -42, -24, 11, -27, -8, 20, 39, -17, -65, -12, -48, 60, -69, -72, -69, 
  34, -2, 58, -14, -40, 68, -11, -46, -34, 40, 85, 51, -52, -67, -17, -36, 9, -79, 81, 53, 
  -30, 78, -56, -12, -61, 81, -12, 30, -62, 74, 85, 35, -2, 45, 52, -79, -38, 100, 76, 52, 
  -61, 69, -46, 79, -24, -86, -27, 64, -84, 1, 78, 66, -28, 43, 20, -44, -42, 88, -48, 51, 
  60, 70, -51, -86, 45, 63, 5, -43, -38, -22, 65, 54, -57, -38, -17, -10, 81, -51, -7, -82, 
  1, 89, 60, 27, -13, 48, 48, -83, 88, -59, -61, 90, 14, -29, -85, 34, 47, -21, -10, 3, 
  55, 48, 48, 27, 80, 17, -84, -4, -14, 39, 93, 30, -2, -74, -9, 90, -61, 75, -37, -1, 
  45, -35, -2, 2, 67, 65, -9, 8, 56, -76, -39, 38, -59, -41, 36, -12, -21, 55, -5, 53, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0053432746790349483, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -50, 176, -23, 154, 2, 61, 24, 28, -55, 87, 150, 103, -24, 40, 116, -8, -20, 102, 80, 163, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0014250286621972919, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*90] = { 
  4, -5, -18, 44, 27, 33, 29, -22, 34, -47, 1, 25, -46, -32, 15, 56, 17, 35, -32, -17, 50, 1, 69, 34, -61, 34, -27, -27, -39, -24, 19, 20, 29, -48, -47, 24, -26, 56, 11, -42, 23, -6, -44, -18, -25, 53, -17, 47, -38, -35, -13, -52, 27, -8, -53, 33, 51, 40, 53, 55, 28, -20, 4, -41, -2, -39, 4, 22, 53, -7, 14, -48, -34, -14, 11, -25, 42, 25, -8, 54, 21, 7, 1, 28, -8, 12, -53, -1, -38, -29, 
  -111, 51, 24, 55, -55, 4, 12, 11, 19, 48, -42, 18, 2, 5, 29, -84, 99, 7, 106, -78, -19, -19, 33, -26, 22, 19, -20, 32, -24, -51, -65, 108, 29, 103, -7, -29, -62, -24, -5, -35, -34, -43, 45, 29, 23, -72, 98, -62, 52, -40, -71, -31, -26, -51, -23, -76, -73, 27, 29, -52, -66, 95, -48, 38, -55, -15, 28, -71, 18, -31, 36, -48, 19, -19, 7, -10, 38, -61, 41, 9, -36, -90, -64, -36, 1, -23, -40, -70, -17, -18, 
  45, -2, -37, -34, 10, -20, 48, 62, 69, 2, -34, 19, -32, 38, -30, 48, 25, 48, 8, 9, 68, -39, 47, -30, 14, -5, 66, 39, -19, -46, -21, 43, 44, -34, -25, -23, -51, -3, 34, -49, 25, 26, -58, -14, 21, -2, -24, -33, 27, -29, 26, -14, -9, 1, 26, -51, 3, 5, 3, -14, 61, -15, 3, 17, -29, 32, 13, -30, -15, -22, -5, -58, 2, 47, -13, -41, -45, 43, -21, -47, 18, -36, 17, -5, -1, 4, -20, -7, -51, -5, 
  -45, 20, -26, 22, 4, 15, -14, 50, 24, -78, 25, 27, 9, 17, 40, -10, -54, -20, 7, 45, -69, 8, -49, -32, -23, -10, -74, 3, 17, 50, -23, 14, 56, -42, 48, -45, 15, -92, -25, -20, -103, -18, -52, -8, 70, -42, -14, -32, 18, 41, -106, -70, -80, -126, -54, -112, -118, -125, -92, 10, 52, 9, 57, 27, -25, -127, -39, -119, -104, -127, -42, -105, -106, -116, 26, 21, -25, 59, 5, 70, -60, -36, -33, -90, -80, -117, -76, -94, -37, -12, 
  101, 26, 9, -42, -37, -32, 74, 20, 9, 37, -9, 21, -25, -15, 25, 86, 48, 36, -11, -4, 0, 75, 16, 20, -21, 6, 48, 46, -46, 21, 82, -23, 49, -43, -12, -36, -14, -41, 28, 20, -4, 9, -58, -29, 93, 22, 58, 35, -13, 43, 33, 45, -35, -3, -22, 51, 33, 41, 47, 93, 10, -31, 54, 52, 8, 46, -4, 83, -28, -3, -38, 28, 53, 33, 82, 87, -5, -14, -29, -17, 58, -32, 57, -9, 31, -19, 27, -26, 54, 38, 
  -40, 64, -5, 0, -21, -33, 9, 56, -26, 30, -39, -8, -44, 39, -29, -25, -32, 2, -15, 5, -38, -50, -14, -41, 53, -7, 23, -1, -20, 20, -35, 15, 30, -31, 12, -34, 54, -24, 31, 72, 60, 42, -20, 4, -33, -80, -22, -53, 2, 35, 63, -3, 19, -26, 40, 48, 32, 5, 45, -40, -8, -34, 23, -42, -15, 14, -16, 44, 45, 44, 69, -12, 53, -28, -102, -61, 13, -26, 40, 0, -33, 23, -34, 38, 11, -31, 29, 8, 69, -53, 
  33, -21, -7, -52, -19, -43, -9, 49, -13, 19, 11, 9, 14, 47, 36, -4, -28, -21, 36, 62, -12, 15, -27, 35, 0, 13, 74, -32, 62, 29, 44, -59, 8, -23, -31, 40, -45, 33, -37, 63, 0, 18, 2, 9, -20, -43, 53, -23, -21, 1, -25, 71, -20, 68, 28, 5, 18, 61, 45, -14, -29, 1, 51, -51, 42, 49, -8, 86, 9, -2, 42, 85, 17, 60, 25, 41, 21, 53, 10, -10, 68, 66, 36, 52, -12, 7, 60, 39, -2, -16, 
  13, -71, 0, 40, 58, 5, 4, 13, -29, 38, -24, 44, -32, 11, -34, -84, -33, -46, -48, 61, 41, -48, -43, -15, -17, 49, -22, 9, -61, -7, -17, 40, -3, -63, -11, -50, -10, 13, 35, -14, -6, 20, 62, 59, 28, -37, -3, -64, -47, 40, -40, -20, -19, 0, -17, -36, -51, 39, 37, -46, -72, -33, 13, -54, 40, 3, -4, -44, -48, 46, -48, -3, -24, 10, 11, -23, -34, 18, -42, 37, 46, -72, 17, -21, 5, -65, 14, 15, 28, -10, 
  30, 57, 41, -18, -40, 36, -3, -30, 0, -12, 3, 35, 34, -21, 23, -25, 25, -21, 49, 21, 52, 44, 59, 32, 32, 35, 41, -6, 47, -37, 31, -54, -2, -5, -41, -28, -57, 46, -39, -8, -41, -41, -64, -34, -39, 17, -18, 2, -34, 23, -59, -56, 62, -30, 21, 21, 2, 21, -12, -14, 38, -12, 60, -27, 10, -50, 59, 53, 48, -27, -21, -13, 14, -42, -11, -51, -41, -14, -36, 55, -23, -22, -30, -10, 51, 17, 3, 26, 38, 38, 
  -72, 18, -38, 22, -59, -6, -87, -32, -63, -102, -91, -80, -98, -55, -51, 23, -14, 45, 66, -62, -45, 13, -9, 34, 16, 3, -30, -16, -35, 10, -49, -24, -31, 24, 13, -19, 7, 14, -37, -30, -25, -13, -68, -23, -38, -81, 30, 34, 75, -68, 10, 30, -83, -82, -51, -8, 13, -14, -73, 5, -75, -39, -30, 70, -28, -45, -87, -50, -73, -6, -67, 7, 19, -30, -25, -67, 46, -1, -34, 22, 13, 34, -73, -58, -54, 29, -56, -47, 11, -4, 
  40, 44, -34, -58, -32, -14, 28, -4, -19, 36, -32, 27, 25, -35, 40, -49, 29, -63, 18, 28, -49, 10, -81, 13, 54, -8, -27, -18, 41, 54, -71, -14, -108, -17, 72, 68, -11, -48, -53, 37, 40, 10, 20, -1, -4, 23, 34, -116, 30, 37, -3, -34, -19, -16, 60, 67, -23, -10, 27, 7, -2, 51, -23, 35, 28, -44, -52, 17, 15, 33, 59, 19, -1, -12, 18, 34, 49, -93, 22, 69, -11, -39, 10, -49, -7, 54, -7, 28, -9, -9, 
  -3, 64, 36, -9, -44, -47, 65, -14, 51, -11, 54, 58, 42, 58, 6, 31, 20, -37, 61, 3, -19, -10, 63, 11, 8, 16, 30, 22, 52, 50, 0, 32, -15, -18, 17, -18, -43, 14, 15, 25, 20, 36, 45, -14, -4, -14, 58, 11, -44, -3, -50, 31, 9, 11, 46, 26, 22, -17, -1, -18, 48, 77, -17, -10, 42, 30, 34, -17, -14, -18, -49, -2, -37, -39, 77, 20, 73, 31, 31, 9, 23, 51, -48, -31, -58, -55, -40, 24, -10, 70, 
  -3, -85, 70, -29, 37, -44, -30, -53, -44, 34, -7, -48, 20, 37, -6, 66, -23, 50, 37, -13, 47, 51, -19, 52, 49, 2, 24, -8, 68, -1, 0, -17, 16, 45, 35, 49, 63, -20, -30, -24, 6, 22, -33, -15, -44, 4, 24, 106, -16, 56, 56, -27, -29, 41, -24, -40, -22, 35, 6, 34, 7, -72, 29, 31, 10, 26, 58, 45, 30, 48, 10, -16, 38, 49, 20, -30, -55, 120, -57, -48, 19, 41, 67, 56, 59, 52, -44, -24, 12, 36, 
  7, -91, -18, -19, 53, 55, -51, 51, -11, 14, 11, 15, 50, 15, -4, -48, -90, 4, -63, -20, -33, -46, -9, -27, -8, -45, -28, 61, 1, 14, 11, -89, -29, -71, -6, 26, 34, 1, 51, -5, 66, 40, 59, -30, 59, -34, -35, 48, 42, 36, 31, 40, -29, -14, 65, -10, 22, 53, 42, 0, -6, -53, 7, -60, 40, 56, 60, 60, 26, 65, -37, 0, 48, 0, 36, -49, -65, -10, 11, -30, -18, 30, -14, -17, 36, 14, 47, 54, 2, -49, 
  58, -54, -12, 19, -3, -96, -85, -38, -30, -44, -7, -119, -112, -6, -44, -17, -56, 32, 40, -53, -10, 3, -80, -9, -117, -94, -68, -106, -14, -7, 64, -37, -3, 40, -11, -101, -108, -48, -15, -116, -121, -16, -118, -25, 3, 42, -27, -17, -52, -25, -75, -38, -45, -74, -107, -101, -12, -78, -14, -20, 9, 18, -19, 58, 7, -12, -19, -35, -82, -31, -57, -99, -12, -88, 58, 34, -32, 27, 2, 6, -34, -60, -106, -94, -52, -110, -21, -59, -112, 18, 
  23, 56, -30, -56, -58, 12, -4, 15, 27, 10, -9, 18, -36, 23, 59, 68, 17, 40, 18, 30, -77, 30, -62, 12, -13, -24, -50, -45, -35, -4, 39, -13, -6, 31, -10, -21, -33, -85, -17, 18, 0, -61, -16, -75, 69, -11, -43, 1, -41, 33, 4, -20, 29, 39, 2, -53, 30, 6, -62, 76, 25, -29, 25, -23, 3, 9, 3, -35, 6, 19, -66, 33, 32, 36, 46, 66, -19, 26, 50, 17, -48, -34, 11, 59, 47, 35, -2, 22, 25, 79, 
  -22, -17, -33, 14, 45, -2, -6, -28, 35, -40, -39, -6, 25, 40, -46, -3, -26, -39, 43, -19, -39, -22, 34, -12, 32, -10, -1, 53, -31, 22, -3, 20, 34, -17, -16, -28, 22, -44, -20, 4, 2, -7, 13, 45, -41, -71, 65, -65, 14, -23, 5, -4, -5, -37, -8, -55, -8, -11, 38, -70, -60, 70, -47, 21, -40, 41, 18, -2, 19, 69, -33, 3, -15, 65, 20, 6, -8, -4, -16, 9, 24, 67, -41, -1, 6, 50, 15, -24, 66, -36, 
  -59, 9, 67, 73, 69, -28, -30, 41, 13, -22, -32, 46, -31, 31, -60, -66, -60, 32, 86, -5, 5, -47, -63, 37, -58, -72, -56, -8, -30, -56, -55, -63, 19, 45, 28, 30, 26, -60, 12, -74, -81, -44, 31, -45, -2, -85, -14, 71, -13, 59, -59, -68, 19, -4, -14, -75, 11, -83, -45, -44, -31, -64, 43, 85, 15, 5, -32, -24, -6, -41, 19, -46, 12, 28, 8, -33, -65, -29, 72, -17, -75, -83, -82, -21, 4, 27, -50, -15, -15, 6, 
  -73, -16, 21, -53, 9, 30, -28, -4, -3, 12, -26, 3, -25, -16, -114, -57, 1, -45, -29, 5, -9, 50, -36, 38, 5, -27, 18, 3, -32, -112, -1, -26, -48, -51, 40, 90, 47, -17, -27, 29, 4, 56, 9, 74, -69, -38, 55, 0, -45, -69, 37, -26, 42, -21, 74, -6, -4, -3, 18, -27, -47, -33, -52, 46, 14, -13, 58, -46, 1, 71, 54, 49, 61, -10, -122, -14, 50, -4, -16, 4, 29, 27, 46, -10, 45, 25, 62, 19, 10, -112, 
  -27, 64, -44, -20, -5, -36, 0, -24, 25, 22, -64, 28, 22, -18, 5, -49, 20, -92, -22, 21, -69, -110, -14, -105, -43, -43, -84, -71, -26, 48, -66, 30, 5, -32, 13, -30, -119, -61, -72, -48, -84, -89, -34, -17, 10, -73, -34, -30, -2, 11, -23, -25, -106, -39, -3, -64, -7, -86, -77, 62, -73, 60, -88, 25, -38, -50, -55, -84, -86, -75, -98, -5, -61, -52, 2, -7, -26, -100, -47, -20, -4, -65, -65, -114, -51, -24, 3, -54, -31, 12, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,90 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0040072663687169552, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.5912209153175354, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.86199718713760376, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,6 } };
const TfArray<1, float> quant9_scale = { 1, { 0.79673933982849121, } };
const TfArray<1, int> quant9_zero = { 1, { 4 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 90, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 96), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_979831_18_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_979831_18_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_979831_18_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_979831_18_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_979831_18_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
